# 데이터 전처리

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

x_train = pd.DataFrame(['남성', '여성', '남성', '여성', '남성', '여성'], columns=['성별'])
x_train.head(3)

성별
0  남성
1  여성
2  남성

In [2]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   성별      6 non-null      object
dtypes: object(1)
memory usage: 176.0+ bytes


In [3]:
x_train['성별'].value_counts()

남성    3
여성    3
Name: 성별, dtype: int64

In [4]:
encoding = LabelEncoder()
encoding.fit(x_train['성별'])
x_train['성별_인코딩'] = encoding.transform(x_train['성별'])

x_train

성별  성별_인코딩
0  남성       0
1  여성       1
2  남성       0
3  여성       1
4  남성       0
5  여성       1

In [5]:
one_encoding = OneHotEncoder(sparse=False)

one_encoding.fit(x_train[['성별']])
one_encoding.transform(x_train[['성별']])

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [6]:
print(one_encoding.get_feature_names())

['x0_남성' 'x0_여성']


C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [7]:
x_train_one = pd.DataFrame(one_encoding.transform(x_train[['성별']]), columns=['성별0', '성별1'])
x_train = pd.concat([x_train, x_train_one], axis=1)
x_train.head(3)

성별  성별_인코딩  성별0  성별1
0  남성       0  1.0  0.0
1  여성       1  0.0  1.0
2  남성       0  1.0  0.0

# 텍스트 데이터 실수화

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    '청년 인재 재능 양성 과정',
    '인공지능 청년 양성',
    '미래 인공지능 데이터 대한민국',
    '데이터 원유 기술사 청년 개발'
]

corpus

['청년 인재 재능 양성 과정', '인공지능 청년 양성', '미래 인공지능 데이터 대한민국', '데이터 원유 기술사 청년 개발']

In [9]:
count_vect = CountVectorizer()
count_vect.fit(corpus)
count_vect.vocabulary_

{'청년': 11,
 '인재': 9,
 '재능': 10,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2,
 '개발': 0}

In [10]:
count_vect.transform(corpus).toarray()

array([[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1]], dtype=int64)

In [11]:
features = count_vect.transform(corpus)
features

<4x12 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [12]:
vocab = count_vect.get_feature_names()
vocab

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '재능', '청년']

In [13]:
DTM = pd.DataFrame(features.toarray(), columns = vocab)
DTM.head()

개발  과정  기술사  대한민국  데이터  미래  양성  원유  인공지능  인재  재능  청년
0   0   1    0     0    0   0   1   0     0   1   1   1
1   0   0    0     0    0   0   1   0     1   0   0   1
2   0   0    0     1    1   1   0   0     1   0   0   0
3   1   0    1     0    1   0   0   1     0   0   0   1

In [14]:
count_vect.transform(['기술사 대한민국 인재 만세']).toarray()

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus

['청년 인재 재능 양성 과정', '인공지능 청년 양성', '미래 인공지능 데이터 대한민국', '데이터 원유 기술사 청년 개발']

In [16]:
tfid = TfidfVectorizer()
tfid.fit(corpus)
tfid.vocabulary_

{'청년': 11,
 '인재': 9,
 '재능': 10,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2,
 '개발': 0}

In [17]:
tfid.transform(corpus).toarray()

array([[0.        , 0.49819711, 0.        , 0.        , 0.        ,
        0.        , 0.39278432, 0.        , 0.        , 0.49819711,
        0.49819711, 0.31799276],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.61366674, 0.        , 0.61366674, 0.        ,
        0.        , 0.49681612],
       [0.        , 0.        , 0.        , 0.55528266, 0.43779123,
        0.55528266, 0.        , 0.        , 0.43779123, 0.        ,
        0.        , 0.        ],
       [0.49819711, 0.        , 0.49819711, 0.        , 0.39278432,
        0.        , 0.        , 0.49819711, 0.        , 0.        ,
        0.        , 0.31799276]])

In [18]:
features_idf = tfid.transform(corpus)

In [19]:
features_idf

<4x12 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [20]:
vocab_idf = count_vect.get_feature_names()
vocab_idf

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '재능', '청년']

In [21]:
DTM_idf = pd.DataFrame(features_idf.toarray(), columns=vocab_idf)
DTM_idf.head()

개발        과정       기술사      대한민국       데이터        미래        양성  \
0  0.000000  0.498197  0.000000  0.000000  0.000000  0.000000  0.392784   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.613667   
2  0.000000  0.000000  0.000000  0.555283  0.437791  0.555283  0.000000   
3  0.498197  0.000000  0.498197  0.000000  0.392784  0.000000  0.000000   

         원유      인공지능        인재        재능        청년  
0  0.000000  0.000000  0.498197  0.498197  0.317993  
1  0.000000  0.613667  0.000000  0.000000  0.496816  
2  0.000000  0.437791  0.000000  0.000000  0.000000  
3  0.498197  0.000000  0.000000  0.000000  0.317993